env:
  browser: true
  es6: true
  webextensions: true
  node: true
parser: babel-eslint
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  browser: readonly
parserOptions:
  ecmaVersion: 7
  sourceType: module
rules:
  strict: 0
  no-console: off
  indent:
    - error
    - 2
    - { SwitchCase: 1 }
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
