env:
  browser: true
  es6: true
  webextensions: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  browser: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: off
  indent:
    - error
    - 2
    - { SwitchCase: 1 }
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
